layer.conf: add missing layer dependencies
Some of the clevis' runtime dependencies are not provided by
openembedded-core:

- tpm2-tools -> meta-tpm (inside meta-security)
- jansson -> meta-oe (inside meta-openembedded)

and then bitbake throws errors such as:

ERROR: Required build target 'clevis' has no buildable providers.
Missing or unbuildable dependency chain was: ['clevis', 'tpm2-tools']

Add meta-oe and meta-tpm to LAYERDEPENDS so clevis can be built.

Signed-off-by: João Marcos Costa <joaomarcos.costa@bootlin.com>